[tool.uv]
python-preference = "3.12"

[tool.uv.dependency-groups.default]
dependencies = [
    "django>=5.0,<6.0",
    "django-allauth>=1.2.0"
]

[tool.uv.dependency-groups.dev]
dependencies = [
    "pytest>=7.3",
    "black>=23.3",
    "mypy>=1.5",
    "flake8>=7.0",
    "pre-commit>=3.3",
    "django-stubs>=3.16"
]
